/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the CSRF token and sets the `ps_csrf` cookie if needed. */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["googleStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/spin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["spin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/bonus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the unresolved bonus on this game so the client can resume it. */
        get: operations["getActiveBonus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/bonus/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bonusAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSpins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Machine-readable error code, e.g. `insufficient_funds` */
            code: string;
            message: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        CsrfToken: {
            token: string;
        };
        AuthProviders: {
            password: boolean;
            google: boolean;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            username: components["schemas"]["Username"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PasswordResetRequest: {
            email: string;
        };
        PasswordResetConfirm: {
            token: string;
            password: string;
        };
        Username: string;
        /**
         * @description One of the preset avatar IDs
         * @enum {string}
         */
        AvatarId: "raven" | "owl" | "serpent" | "scarab" | "wolf" | "phoenix" | "kitsune" | "spider" | "fox" | "comet";
        Me: {
            /** Format: uuid */
            id: string;
            email: string;
            username: components["schemas"]["Username"];
            avatar: components["schemas"]["AvatarId"];
            balance: components["schemas"]["Coins"];
            hasPassword: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateProfileRequest: {
            username?: components["schemas"]["Username"];
            avatar?: components["schemas"]["AvatarId"];
        };
        /**
         * Format: int64
         * @description Play-money amount. Always an integer number of Coins.
         */
        Coins: number;
        Wallet: {
            balance: components["schemas"]["Coins"];
        };
        /** @enum {string} */
        TransactionKind: "signup_bonus" | "spin_bet" | "spin_win" | "bonus_win" | "daily_bonus" | "hourly_bonus" | "refill";
        Transaction: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["TransactionKind"];
            /**
             * Format: int64
             * @description Signed change in balance
             */
            amount: number;
            balanceAfter: components["schemas"]["Coins"];
            gameId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        TransactionPage: {
            items: components["schemas"]["Transaction"][];
            /**
             * Format: int64
             * @description Pass as `before` to get the next page. Absent on the last page.
             */
            nextBefore?: number;
        };
        /** @enum {string} */
        Volatility: "low" | "medium" | "high" | "very_high";
        /**
         * @description How the grid is shaped. The renderer picks its layout from this.
         * @enum {string}
         */
        LayoutKind: "ways" | "lines" | "cluster" | "megaways" | "hex";
        GameInfo: {
            id: string;
            name: string;
            theme: string;
            description?: string;
            layout: components["schemas"]["LayoutKind"];
            reels: number;
            /** @description Row count, or the maximum row count for variable-height layouts */
            rows: number;
            volatility: components["schemas"]["Volatility"];
            betLevels: components["schemas"]["Coins"][];
            defaultBet: components["schemas"]["Coins"];
            tags: ("new" | "hot")[];
        };
        SpinRequest: {
            bet: components["schemas"]["Coins"];
        };
        Position: {
            reel: number;
            row: number;
        };
        /**
         * @description Symbol IDs by reel (column), each from top to bottom. Reels may differ in
         *     length (Megaways). Hex grids use offset columns: `reel` is the column and
         *     `row` the cell within it.
         */
        Grid: string[][];
        Win: {
            symbol: string;
            positions: components["schemas"]["Position"][];
            amount: components["schemas"]["Coins"];
            /** @description Total multiplier applied to this win (1 when none) */
            multiplier?: number;
            /** @description Ways-pay games only */
            ways?: number;
            /** @description Line-pay games only */
            line?: number;
            /** @description Symbols matched (reels for ways/lines, cluster size for clusters) */
            count?: number;
        };
        /**
         * @description A visual event the client animates in order, e.g. `wild_added`,
         *     `multiplier`, `symbol_transform`, `serpent_move`, `lava_spread`.
         *     `positions` is what the event affects; `data` holds event-specific
         *     values whose shape each game documents.
         */
        GameEvent: {
            type: string;
            positions?: components["schemas"]["Position"][];
            symbol?: string;
            /** Format: int64 */
            value?: number;
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description One grid state. A spin without cascades has one step. For cascades,
         *     each step's `removed` positions are cleared and `grid` of the next step
         *     is the board after symbols drop in.
         */
        SpinStep: {
            grid: components["schemas"]["Grid"];
            /** @description Events to play before evaluating this step's wins */
            events?: components["schemas"]["GameEvent"][];
            wins: components["schemas"]["Win"][];
            removed?: components["schemas"]["Position"][];
            /** @description Step multiplier (cascade multipliers etc.), 1 when none */
            multiplier?: number;
            stepWin: components["schemas"]["Coins"];
        };
        BonusTrigger: {
            kind: components["schemas"]["BonusKind"];
            /** @description The symbols that triggered the bonus */
            positions: components["schemas"]["Position"][];
            /** @description Reels on which to play the slow-down near-trigger animation */
            anticipation?: number[];
        };
        /** @description The animated part of a spin; reused by free-spin bonus steps. */
        SpinOutcome: {
            steps: components["schemas"]["SpinStep"][];
            /** @description Events after all steps (e.g. end-of-spin multipliers) */
            events?: components["schemas"]["GameEvent"][];
            totalWin: components["schemas"]["Coins"];
            /** @description Reels to spin slower because a feature may land */
            anticipation?: number[];
        };
        /**
         * @description Celebration level, chosen by the server from win / bet
         * @enum {string}
         */
        WinTier: "none" | "normal" | "big" | "mega" | "epic";
        SpinResult: {
            /** Format: uuid */
            spinId: string;
            gameId: string;
            bet: components["schemas"]["Coins"];
            outcome: components["schemas"]["SpinOutcome"];
            totalWin: components["schemas"]["Coins"];
            winTier: components["schemas"]["WinTier"];
            balance: components["schemas"]["Coins"];
            bonusTrigger?: components["schemas"]["BonusTrigger"];
            bonus?: components["schemas"]["BonusState"];
        };
        /** @enum {string} */
        BonusKind: "free_spins" | "pick" | "ladder" | "wheel" | "plinko" | "trail" | "hold_and_win" | "timing" | "route";
        /** @enum {string} */
        BonusStatus: "active" | "completed";
        /**
         * @description The public part of a bonus state machine. Hidden values (e.g. what an
         *     unpicked tile contains) never leave the server.
         */
        BonusState: {
            /** Format: uuid */
            bonusId: string;
            gameId: string;
            kind: components["schemas"]["BonusKind"];
            status: components["schemas"]["BonusStatus"];
            bet: components["schemas"]["Coins"];
            totalWin: components["schemas"]["Coins"];
            /** @description Number of actions taken so far */
            step: number;
            /** @description Actions the player may send next, e.g. `spin`, `pick`, `choose` */
            actions: components["schemas"]["BonusActionOption"][];
            /** @description Game-specific public state (spins left, picked tiles, ladder rung…) */
            data: {
                [key: string]: unknown;
            };
        };
        BonusActionOption: {
            action: string;
            /** @description Valid values for `choice`, when the action takes one */
            choices?: string[];
        };
        BonusActionRequest: {
            action: string;
            choice?: string;
            /**
             * @description The `step` of the state the client acted on. A mismatch returns 409,
             *     which makes double-clicks and retries safe.
             */
            step: number;
        };
        BonusStepResult: {
            state: components["schemas"]["BonusState"];
            stepWin: components["schemas"]["Coins"];
            balance: components["schemas"]["Coins"];
            outcome?: components["schemas"]["SpinOutcome"];
            /** @description What this action revealed (pick contents, wheel segment, …) */
            reveal?: {
                [key: string]: unknown;
            };
        };
        SpinHistoryItem: {
            /** Format: uuid */
            spinId: string;
            gameId: string;
            bet: components["schemas"]["Coins"];
            win: components["schemas"]["Coins"];
            bonusTriggered?: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        SpinHistoryPage: {
            items: components["schemas"]["SpinHistoryItem"][];
            /** Format: uuid */
            nextBefore?: string;
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not signed in, or bad credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GameId: string;
        Limit: number;
        /** @description Return items with an ID lower than this (cursor) */
        BeforeId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and signed in. Sets the session cookie. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. Sets the session cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. Clears the session cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /**
             * @description Always returned, whether or not the email exists, so the endpoint
             *     cannot be used to discover accounts.
             */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password changed. All existing sessions are revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Which sign-in methods are enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProviders"];
                };
            };
        };
    };
    googleStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    googleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back to the web app */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Return items with an ID lower than this (cursor) */
                before?: components["parameters"]["BeforeId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameInfo"][];
                };
            };
        };
    };
    spin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpinRequest"];
            };
        };
        responses: {
            /** @description The full, pre-computed spin result to animate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpinResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description `insufficient_funds`, or `bonus_in_progress` when a bonus on this
             *     game must be resolved first.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getActiveBonus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active bonus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BonusState"];
                };
            };
            /** @description No active bonus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    bonusAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BonusActionRequest"];
            };
        };
        responses: {
            /** @description The step outcome and the new bonus state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BonusStepResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listSpins: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Return spins created before this spin ID (cursor) */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpinHistoryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
