// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bonus.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getActiveBonus = `-- name: GetActiveBonus :one
SELECT id, user_id, game_id, spin_id, kind, status, bet, total_win, step, state, created_at, updated_at, completed_at FROM bonus_sessions
WHERE user_id = $1 AND game_id = $2 AND status = 'active'
`

type GetActiveBonusParams struct {
	UserID uuid.UUID
	GameID string
}

func (q *Queries) GetActiveBonus(ctx context.Context, arg GetActiveBonusParams) (BonusSession, error) {
	row := q.db.QueryRow(ctx, getActiveBonus, arg.UserID, arg.GameID)
	var i BonusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.SpinID,
		&i.Kind,
		&i.Status,
		&i.Bet,
		&i.TotalWin,
		&i.Step,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertBonus = `-- name: InsertBonus :exec
INSERT INTO bonus_sessions (id, user_id, game_id, spin_id, kind, status, bet, total_win, step, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertBonusParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	GameID   string
	SpinID   uuid.UUID
	Kind     string
	Status   string
	Bet      int64
	TotalWin int64
	Step     int32
	State    []byte
}

func (q *Queries) InsertBonus(ctx context.Context, arg InsertBonusParams) error {
	_, err := q.db.Exec(ctx, insertBonus,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.SpinID,
		arg.Kind,
		arg.Status,
		arg.Bet,
		arg.TotalWin,
		arg.Step,
		arg.State,
	)
	return err
}

const lockActiveBonus = `-- name: LockActiveBonus :one
SELECT id, user_id, game_id, spin_id, kind, status, bet, total_win, step, state, created_at, updated_at, completed_at FROM bonus_sessions
WHERE user_id = $1 AND game_id = $2 AND status = 'active'
FOR UPDATE
`

type LockActiveBonusParams struct {
	UserID uuid.UUID
	GameID string
}

// Must run inside a transaction, after locking the wallet.
func (q *Queries) LockActiveBonus(ctx context.Context, arg LockActiveBonusParams) (BonusSession, error) {
	row := q.db.QueryRow(ctx, lockActiveBonus, arg.UserID, arg.GameID)
	var i BonusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.SpinID,
		&i.Kind,
		&i.Status,
		&i.Bet,
		&i.TotalWin,
		&i.Step,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const sumBonusWins = `-- name: SumBonusWins :one
SELECT coalesce(sum(total_win), 0)::bigint FROM bonus_sessions WHERE user_id = $1
`

func (q *Queries) SumBonusWins(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumBonusWins, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateBonus = `-- name: UpdateBonus :exec
UPDATE bonus_sessions
SET status       = $2,
    total_win    = $3,
    step         = $4,
    state        = $5,
    updated_at   = now(),
    completed_at = CASE WHEN $2 = 'completed' THEN now() ELSE NULL END
WHERE id = $1
`

type UpdateBonusParams struct {
	ID       uuid.UUID
	Status   string
	TotalWin int64
	Step     int32
	State    []byte
}

func (q *Queries) UpdateBonus(ctx context.Context, arg UpdateBonusParams) error {
	_, err := q.db.Exec(ctx, updateBonus,
		arg.ID,
		arg.Status,
		arg.TotalWin,
		arg.Step,
		arg.State,
	)
	return err
}
