// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type BonusSession struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	GameID      string
	SpinID      uuid.UUID
	Kind        string
	Status      string
	Bet         int64
	TotalWin    int64
	Step        int32
	State       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt *time.Time
}

type PasswordResetToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Spin struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GameID    string
	Bet       int64
	Win       int64
	BonusID   *uuid.UUID
	Result    []byte
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	PasswordHash *string
	GoogleSub    *string
	Avatar       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Wallet struct {
	UserID            uuid.UUID
	Balance           int64
	DailyStreak       int32
	LastDailyClaimAt  *time.Time
	LastHourlyClaimAt *time.Time
	LastRefillAt      *time.Time
	UpdatedAt         time.Time
}

type WalletTransaction struct {
	ID           int64
	UserID       uuid.UUID
	Kind         string
	Amount       int64
	BalanceAfter int64
	GameID       *string
	SpinID       *uuid.UUID
	BonusID      *uuid.UUID
	CreatedAt    time.Time
}
