// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: spins.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSpin = `-- name: InsertSpin :exec
INSERT INTO spins (id, user_id, game_id, bet, win, bonus_id, result)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSpinParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	GameID  string
	Bet     int64
	Win     int64
	BonusID *uuid.UUID
	Result  []byte
}

func (q *Queries) InsertSpin(ctx context.Context, arg InsertSpinParams) error {
	_, err := q.db.Exec(ctx, insertSpin,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.Bet,
		arg.Win,
		arg.BonusID,
		arg.Result,
	)
	return err
}

const listSpins = `-- name: ListSpins :many
SELECT sp.id, sp.game_id, sp.bet, sp.win, sp.bonus_id, sp.created_at FROM spins sp
WHERE sp.user_id = $1::uuid
  AND ($2::uuid IS NULL OR (sp.created_at, sp.id) < (
        SELECT c.created_at, c.id FROM spins c
        WHERE c.id = $2::uuid AND c.user_id = $1::uuid))
ORDER BY sp.created_at DESC, sp.id DESC
LIMIT $3
`

type ListSpinsParams struct {
	UserID uuid.UUID
	Before *uuid.UUID
	Lim    int32
}

type ListSpinsRow struct {
	ID        uuid.UUID
	GameID    string
	Bet       int64
	Win       int64
	BonusID   *uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) ListSpins(ctx context.Context, arg ListSpinsParams) ([]ListSpinsRow, error) {
	rows, err := q.db.Query(ctx, listSpins, arg.UserID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpinsRow{}
	for rows.Next() {
		var i ListSpinsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Bet,
			&i.Win,
			&i.BonusID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSpins = `-- name: SumSpins :one
SELECT count(*)::bigint AS spins, coalesce(sum(bet), 0)::bigint AS bets, coalesce(sum(win), 0)::bigint AS wins
FROM spins WHERE user_id = $1
`

type SumSpinsRow struct {
	Spins int64
	Bets  int64
	Wins  int64
}

// Totals used by consistency tests and stats.
func (q *Queries) SumSpins(ctx context.Context, userID uuid.UUID) (SumSpinsRow, error) {
	row := q.db.QueryRow(ctx, sumSpins, userID)
	var i SumSpinsRow
	err := row.Scan(&i.Spins, &i.Bets, &i.Wins)
	return i, err
}
