// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id, balance) VALUES ($1, $2)
`

type CreateWalletParams struct {
	UserID  uuid.UUID
	Balance int64
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.Exec(ctx, createWallet, arg.UserID, arg.Balance)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT balance FROM wallets WHERE user_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO wallet_transactions (user_id, kind, amount, balance_after, game_id, spin_id, bonus_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTransactionParams struct {
	UserID       uuid.UUID
	Kind         string
	Amount       int64
	BalanceAfter int64
	GameID       *string
	SpinID       *uuid.UUID
	BonusID      *uuid.UUID
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.UserID,
		arg.Kind,
		arg.Amount,
		arg.BalanceAfter,
		arg.GameID,
		arg.SpinID,
		arg.BonusID,
	)
	return err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, kind, amount, balance_after, game_id, spin_id, bonus_id, created_at FROM wallet_transactions
WHERE user_id = $1
  AND ($2::bigint IS NULL OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListTransactionsParams struct {
	UserID uuid.UUID
	Before *int64
	Lim    int32
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Amount,
			&i.BalanceAfter,
			&i.GameID,
			&i.SpinID,
			&i.BonusID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWallet = `-- name: LockWallet :one
SELECT user_id, balance, daily_streak, last_daily_claim_at, last_hourly_claim_at, last_refill_at, updated_at FROM wallets WHERE user_id = $1 FOR UPDATE
`

// Must run inside a transaction. Serialises all balance changes for a user.
func (q *Queries) LockWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.DailyStreak,
		&i.LastDailyClaimAt,
		&i.LastHourlyClaimAt,
		&i.LastRefillAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setBalance = `-- name: SetBalance :exec
UPDATE wallets SET balance = $2, updated_at = now() WHERE user_id = $1
`

type SetBalanceParams struct {
	UserID  uuid.UUID
	Balance int64
}

func (q *Queries) SetBalance(ctx context.Context, arg SetBalanceParams) error {
	_, err := q.db.Exec(ctx, setBalance, arg.UserID, arg.Balance)
	return err
}
