// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarId.
const (
	Comet   AvatarId = "comet"
	Fox     AvatarId = "fox"
	Kitsune AvatarId = "kitsune"
	Owl     AvatarId = "owl"
	Phoenix AvatarId = "phoenix"
	Raven   AvatarId = "raven"
	Scarab  AvatarId = "scarab"
	Serpent AvatarId = "serpent"
	Spider  AvatarId = "spider"
	Wolf    AvatarId = "wolf"
)

// Valid indicates whether the value is a known member of the AvatarId enum.
func (e AvatarId) Valid() bool {
	switch e {
	case Comet:
		return true
	case Fox:
		return true
	case Kitsune:
		return true
	case Owl:
		return true
	case Phoenix:
		return true
	case Raven:
		return true
	case Scarab:
		return true
	case Serpent:
		return true
	case Spider:
		return true
	case Wolf:
		return true
	default:
		return false
	}
}

// Defines values for BonusKind.
const (
	FreeSpins  BonusKind = "free_spins"
	HoldAndWin BonusKind = "hold_and_win"
	Ladder     BonusKind = "ladder"
	Pick       BonusKind = "pick"
	Plinko     BonusKind = "plinko"
	Route      BonusKind = "route"
	Timing     BonusKind = "timing"
	Trail      BonusKind = "trail"
	Wheel      BonusKind = "wheel"
)

// Valid indicates whether the value is a known member of the BonusKind enum.
func (e BonusKind) Valid() bool {
	switch e {
	case FreeSpins:
		return true
	case HoldAndWin:
		return true
	case Ladder:
		return true
	case Pick:
		return true
	case Plinko:
		return true
	case Route:
		return true
	case Timing:
		return true
	case Trail:
		return true
	case Wheel:
		return true
	default:
		return false
	}
}

// Defines values for BonusStatus.
const (
	Active    BonusStatus = "active"
	Completed BonusStatus = "completed"
)

// Valid indicates whether the value is a known member of the BonusStatus enum.
func (e BonusStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Completed:
		return true
	default:
		return false
	}
}

// Defines values for GameInfoTags.
const (
	Hot GameInfoTags = "hot"
	New GameInfoTags = "new"
)

// Valid indicates whether the value is a known member of the GameInfoTags enum.
func (e GameInfoTags) Valid() bool {
	switch e {
	case Hot:
		return true
	case New:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for LayoutKind.
const (
	Cluster  LayoutKind = "cluster"
	Hex      LayoutKind = "hex"
	Lines    LayoutKind = "lines"
	Megaways LayoutKind = "megaways"
	Ways     LayoutKind = "ways"
)

// Valid indicates whether the value is a known member of the LayoutKind enum.
func (e LayoutKind) Valid() bool {
	switch e {
	case Cluster:
		return true
	case Hex:
		return true
	case Lines:
		return true
	case Megaways:
		return true
	case Ways:
		return true
	default:
		return false
	}
}

// Defines values for TransactionKind.
const (
	BonusWin    TransactionKind = "bonus_win"
	DailyBonus  TransactionKind = "daily_bonus"
	HourlyBonus TransactionKind = "hourly_bonus"
	Refill      TransactionKind = "refill"
	SignupBonus TransactionKind = "signup_bonus"
	SpinBet     TransactionKind = "spin_bet"
	SpinWin     TransactionKind = "spin_win"
)

// Valid indicates whether the value is a known member of the TransactionKind enum.
func (e TransactionKind) Valid() bool {
	switch e {
	case BonusWin:
		return true
	case DailyBonus:
		return true
	case HourlyBonus:
		return true
	case Refill:
		return true
	case SignupBonus:
		return true
	case SpinBet:
		return true
	case SpinWin:
		return true
	default:
		return false
	}
}

// Defines values for Volatility.
const (
	High     Volatility = "high"
	Low      Volatility = "low"
	Medium   Volatility = "medium"
	VeryHigh Volatility = "very_high"
)

// Valid indicates whether the value is a known member of the Volatility enum.
func (e Volatility) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case VeryHigh:
		return true
	default:
		return false
	}
}

// Defines values for WinTier.
const (
	Big    WinTier = "big"
	Epic   WinTier = "epic"
	Mega   WinTier = "mega"
	None   WinTier = "none"
	Normal WinTier = "normal"
)

// Valid indicates whether the value is a known member of the WinTier enum.
func (e WinTier) Valid() bool {
	switch e {
	case Big:
		return true
	case Epic:
		return true
	case Mega:
		return true
	case None:
		return true
	case Normal:
		return true
	default:
		return false
	}
}

// AuthProviders defines model for AuthProviders.
type AuthProviders struct {
	Google   bool `json:"google"`
	Password bool `json:"password"`
}

// AvatarId One of the preset avatar IDs
type AvatarId string

// BonusActionOption defines model for BonusActionOption.
type BonusActionOption struct {
	Action string `json:"action"`

	// Choices Valid values for `choice`, when the action takes one
	Choices []string `json:"choices,omitempty,omitzero"`
}

// BonusActionRequest defines model for BonusActionRequest.
type BonusActionRequest struct {
	Action string `json:"action"`
	Choice string `json:"choice,omitempty,omitzero"`

	// Step The `step` of the state the client acted on. A mismatch returns 409,
	// which makes double-clicks and retries safe.
	Step int `json:"step"`
}

// BonusKind defines model for BonusKind.
type BonusKind string

// BonusState The public part of a bonus state machine. Hidden values (e.g. what an
// unpicked tile contains) never leave the server.
type BonusState struct {
	// Actions Actions the player may send next, e.g. `spin`, `pick`, `choose`
	Actions []BonusActionOption `json:"actions"`

	// Bet Play-money amount. Always an integer number of Coins.
	Bet     Coins              `json:"bet"`
	BonusId openapi_types.UUID `json:"bonusId"`

	// Data Game-specific public state (spins left, picked tiles, ladder rung…)
	Data   map[string]interface{} `json:"data"`
	GameId string                 `json:"gameId"`
	Kind   BonusKind              `json:"kind"`
	Status BonusStatus            `json:"status"`

	// Step Number of actions taken so far
	Step int `json:"step"`

	// TotalWin Play-money amount. Always an integer number of Coins.
	TotalWin Coins `json:"totalWin"`
}

// BonusStatus defines model for BonusStatus.
type BonusStatus string

// BonusStepResult defines model for BonusStepResult.
type BonusStepResult struct {
	// Balance Play-money amount. Always an integer number of Coins.
	Balance Coins `json:"balance"`

	// Outcome The animated part of a spin; reused by free-spin bonus steps.
	Outcome SpinOutcome `json:"outcome,omitempty,omitzero"`

	// Reveal What this action revealed (pick contents, wheel segment, …)
	Reveal map[string]interface{} `json:"reveal,omitempty,omitzero"`

	// State The public part of a bonus state machine. Hidden values (e.g. what an
	// unpicked tile contains) never leave the server.
	State BonusState `json:"state"`

	// StepWin Play-money amount. Always an integer number of Coins.
	StepWin Coins `json:"stepWin"`

	// WinTier Celebration level, chosen by the server from win / bet
	WinTier WinTier `json:"winTier"`
}

// BonusTrigger defines model for BonusTrigger.
type BonusTrigger struct {
	// Anticipation Reels on which to play the slow-down near-trigger animation
	Anticipation []int `json:"anticipation,omitempty,omitzero"`

	// Data What the trigger decided, for the reveal animation (e.g. which god
	// the bonus symbols chose and how many free spins were awarded).
	Data map[string]interface{} `json:"data,omitempty,omitzero"`
	Kind BonusKind              `json:"kind"`

	// Positions The symbols that triggered the bonus
	Positions []Position `json:"positions"`
}

// Coins Play-money amount. Always an integer number of Coins.
type Coins = int64

// CsrfToken defines model for CsrfToken.
type CsrfToken struct {
	Token string `json:"token"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code, e.g. `insufficient_funds`
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GameEvent A visual event the client animates in order, e.g. `wild_added`,
// `multiplier`, `symbol_transform`, `serpent_move`, `lava_spread`.
// `positions` is what the event affects; `data` holds event-specific
// values whose shape each game documents.
type GameEvent struct {
	Data      map[string]interface{} `json:"data,omitempty,omitzero"`
	Positions []Position             `json:"positions,omitempty,omitzero"`
	Symbol    string                 `json:"symbol,omitempty,omitzero"`
	Type      string                 `json:"type"`
	Value     int64                  `json:"value,omitempty,omitzero"`
}

// GameInfo defines model for GameInfo.
type GameInfo struct {
	BetLevels []Coins `json:"betLevels"`

	// DefaultBet Play-money amount. Always an integer number of Coins.
	DefaultBet  Coins  `json:"defaultBet"`
	Description string `json:"description,omitempty,omitzero"`
	Id          string `json:"id"`

	// Layout How the grid is shaped. The renderer picks its layout from this.
	Layout LayoutKind `json:"layout"`
	Name   string     `json:"name"`
	Reels  int        `json:"reels"`

	// Rows Row count, or the maximum row count for variable-height layouts
	Rows       int            `json:"rows"`
	Tags       []GameInfoTags `json:"tags"`
	Theme      string         `json:"theme"`
	Volatility Volatility     `json:"volatility"`
}

// GameInfoTags defines model for GameInfo.Tags.
type GameInfoTags string

// Grid Symbol IDs by reel (column), each from top to bottom. Reels may differ in
// length (Megaways). Hex grids use offset columns: `reel` is the column and
// `row` the cell within it.
type Grid = [][]string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LayoutKind How the grid is shaped. The renderer picks its layout from this.
type LayoutKind string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	// Avatar One of the preset avatar IDs
	Avatar AvatarId `json:"avatar"`

	// Balance Play-money amount. Always an integer number of Coins.
	Balance     Coins              `json:"balance"`
	CreatedAt   time.Time          `json:"createdAt"`
	Email       string             `json:"email"`
	HasPassword bool               `json:"hasPassword"`
	Id          openapi_types.UUID `json:"id"`
	Username    Username           `json:"username"`
}

// PasswordResetConfirm defines model for PasswordResetConfirm.
type PasswordResetConfirm struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email string `json:"email"`
}

// Position defines model for Position.
type Position struct {
	Reel int `json:"reel"`
	Row  int `json:"row"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username Username            `json:"username"`
}

// SpinHistoryItem defines model for SpinHistoryItem.
type SpinHistoryItem struct {
	// Bet Play-money amount. Always an integer number of Coins.
	Bet            Coins              `json:"bet"`
	BonusTriggered bool               `json:"bonusTriggered,omitempty,omitzero"`
	CreatedAt      time.Time          `json:"createdAt"`
	GameId         string             `json:"gameId"`
	SpinId         openapi_types.UUID `json:"spinId"`

	// Win Play-money amount. Always an integer number of Coins.
	Win Coins `json:"win"`
}

// SpinHistoryPage defines model for SpinHistoryPage.
type SpinHistoryPage struct {
	Items      []SpinHistoryItem  `json:"items"`
	NextBefore openapi_types.UUID `json:"nextBefore,omitempty,omitzero"`
}

// SpinOutcome The animated part of a spin; reused by free-spin bonus steps.
type SpinOutcome struct {
	// Anticipation Reels to spin slower because a feature may land
	Anticipation []int `json:"anticipation,omitempty,omitzero"`

	// Events Events after all steps (e.g. end-of-spin multipliers)
	Events []GameEvent `json:"events,omitempty,omitzero"`
	Steps  []SpinStep  `json:"steps"`

	// TotalWin Play-money amount. Always an integer number of Coins.
	TotalWin Coins `json:"totalWin"`
}

// SpinRequest defines model for SpinRequest.
type SpinRequest struct {
	// Bet Play-money amount. Always an integer number of Coins.
	Bet Coins `json:"bet"`
}

// SpinResult defines model for SpinResult.
type SpinResult struct {
	// Balance Play-money amount. Always an integer number of Coins.
	Balance Coins `json:"balance"`

	// Bet Play-money amount. Always an integer number of Coins.
	Bet Coins `json:"bet"`

	// Bonus The public part of a bonus state machine. Hidden values (e.g. what an
	// unpicked tile contains) never leave the server.
	Bonus        BonusState   `json:"bonus,omitempty,omitzero"`
	BonusTrigger BonusTrigger `json:"bonusTrigger,omitempty,omitzero"`
	GameId       string       `json:"gameId"`

	// Outcome The animated part of a spin; reused by free-spin bonus steps.
	Outcome SpinOutcome        `json:"outcome"`
	SpinId  openapi_types.UUID `json:"spinId"`

	// TotalWin Play-money amount. Always an integer number of Coins.
	TotalWin Coins `json:"totalWin"`

	// WinTier Celebration level, chosen by the server from win / bet
	WinTier WinTier `json:"winTier"`
}

// SpinStep One grid state. A spin without cascades has one step. For cascades,
// each step's `removed` positions are cleared and `grid` of the next step
// is the board after symbols drop in.
type SpinStep struct {
	// Events Events to play before evaluating this step's wins
	Events []GameEvent `json:"events,omitempty,omitzero"`

	// Grid Symbol IDs by reel (column), each from top to bottom. Reels may differ in
	// length (Megaways). Hex grids use offset columns: `reel` is the column and
	// `row` the cell within it.
	Grid Grid `json:"grid"`

	// Multiplier Step multiplier (cascade multipliers etc.), 1 when none
	Multiplier int        `json:"multiplier,omitempty,omitzero"`
	Removed    []Position `json:"removed,omitempty,omitzero"`

	// StepWin Play-money amount. Always an integer number of Coins.
	StepWin Coins `json:"stepWin"`
	Wins    []Win `json:"wins"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Amount Signed change in balance
	Amount int64 `json:"amount"`

	// BalanceAfter Play-money amount. Always an integer number of Coins.
	BalanceAfter Coins           `json:"balanceAfter"`
	CreatedAt    time.Time       `json:"createdAt"`
	GameId       string          `json:"gameId,omitempty,omitzero"`
	Id           int64           `json:"id"`
	Kind         TransactionKind `json:"kind"`
}

// TransactionKind defines model for TransactionKind.
type TransactionKind string

// TransactionPage defines model for TransactionPage.
type TransactionPage struct {
	Items []Transaction `json:"items"`

	// NextBefore Pass as `before` to get the next page. Absent on the last page.
	NextBefore int64 `json:"nextBefore,omitempty,omitzero"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	// Avatar One of the preset avatar IDs
	Avatar   AvatarId `json:"avatar,omitempty,omitzero"`
	Username Username `json:"username,omitempty,omitzero"`
}

// Username defines model for Username.
type Username = string

// Volatility defines model for Volatility.
type Volatility string

// Wallet defines model for Wallet.
type Wallet struct {
	// Balance Play-money amount. Always an integer number of Coins.
	Balance Coins `json:"balance"`
}

// Win defines model for Win.
type Win struct {
	// Amount Play-money amount. Always an integer number of Coins.
	Amount Coins `json:"amount"`

	// Count Symbols matched (reels for ways/lines, cluster size for clusters)
	Count int `json:"count,omitempty,omitzero"`

	// Line Line-pay games only
	Line int `json:"line,omitempty,omitzero"`

	// Multiplier Total multiplier applied to this win (1 when none)
	Multiplier int        `json:"multiplier,omitempty,omitzero"`
	Positions  []Position `json:"positions"`
	Symbol     string     `json:"symbol"`

	// Ways Ways-pay games only
	Ways int `json:"ways,omitempty,omitzero"`
}

// WinTier Celebration level, chosen by the server from win / bet
type WinTier string

// BeforeId defines model for BeforeId.
type BeforeId = int64

// GameId defines model for GameId.
type GameId = string

// Limit defines model for Limit.
type Limit = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	Code  string `form:"code,omitempty" json:"code,omitempty,omitzero"`
	State string `form:"state,omitempty" json:"state,omitempty,omitzero"`
	Error string `form:"error,omitempty" json:"error,omitempty,omitzero"`
}

// ListSpinsParams defines parameters for ListSpins.
type ListSpinsParams struct {
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Before Return spins created before this spin ID (cursor)
	Before openapi_types.UUID `form:"before,omitempty" json:"before,omitempty,omitzero"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Before Return items with an ID lower than this (cursor)
	Before BeforeId `form:"before,omitempty" json:"before,omitempty,omitzero"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirm

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// BonusActionJSONRequestBody defines body for BonusAction for application/json ContentType.
type BonusActionJSONRequestBody = BonusActionRequest

// SpinJSONRequestBody defines body for Spin for application/json ContentType.
type SpinJSONRequestBody = SpinRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /auth/csrf)
	GetCsrfToken(w http.ResponseWriter, r *http.Request)

	// (GET /auth/google/callback)
	GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams)

	// (GET /auth/google/start)
	GoogleStart(w http.ResponseWriter, r *http.Request)

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/password-reset/confirm)
	ConfirmPasswordReset(w http.ResponseWriter, r *http.Request)

	// (POST /auth/password-reset/request)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)

	// (GET /auth/providers)
	GetAuthProviders(w http.ResponseWriter, r *http.Request)

	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)

	// (GET /games)
	ListGames(w http.ResponseWriter, r *http.Request)

	// (GET /games/{gameId}/bonus)
	GetActiveBonus(w http.ResponseWriter, r *http.Request, gameId GameId)

	// (POST /games/{gameId}/bonus/actions)
	BonusAction(w http.ResponseWriter, r *http.Request, gameId GameId)

	// (POST /games/{gameId}/spin)
	Spin(w http.ResponseWriter, r *http.Request, gameId GameId)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)

	// (GET /spins)
	ListSpins(w http.ResponseWriter, r *http.Request, params ListSpinsParams)

	// (GET /wallet)
	GetWallet(w http.ResponseWriter, r *http.Request)

	// (GET /wallet/transactions)
	ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /auth/csrf)
func (_ Unimplemented) GetCsrfToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/google/callback)
func (_ Unimplemented) GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/google/start)
func (_ Unimplemented) GoogleStart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/password-reset/confirm)
func (_ Unimplemented) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/password-reset/request)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/providers)
func (_ Unimplemented) GetAuthProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /games)
func (_ Unimplemented) ListGames(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /games/{gameId}/bonus)
func (_ Unimplemented) GetActiveBonus(w http.ResponseWriter, r *http.Request, gameId GameId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /games/{gameId}/bonus/actions)
func (_ Unimplemented) BonusAction(w http.ResponseWriter, r *http.Request, gameId GameId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /games/{gameId}/spin)
func (_ Unimplemented) Spin(w http.ResponseWriter, r *http.Request, gameId GameId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /me)
func (_ Unimplemented) UpdateMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /spins)
func (_ Unimplemented) ListSpins(w http.ResponseWriter, r *http.Request, params ListSpinsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /wallet)
func (_ Unimplemented) GetWallet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /wallet/transactions)
func (_ Unimplemented) ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCsrfToken operation middleware
func (siw *ServerInterfaceWrapper) GetCsrfToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCsrfToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleStart operation middleware
func (siw *ServerInterfaceWrapper) GoogleStart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleStart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthProviders operation middleware
func (siw *ServerInterfaceWrapper) GetAuthProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActiveBonus operation middleware
func (siw *ServerInterfaceWrapper) GetActiveBonus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", chi.URLParam(r, "gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveBonus(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BonusAction operation middleware
func (siw *ServerInterfaceWrapper) BonusAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", chi.URLParam(r, "gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BonusAction(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Spin operation middleware
func (siw *ServerInterfaceWrapper) Spin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", chi.URLParam(r, "gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Spin(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSpins operation middleware
func (siw *ServerInterfaceWrapper) ListSpins(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSpinsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSpins(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWallet operation middleware
func (siw *ServerInterfaceWrapper) GetWallet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWallet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/csrf", wrapper.GetCsrfToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset/request", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/providers", wrapper.GetAuthProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/start", wrapper.GoogleStart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/callback", wrapper.GoogleCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wallet", wrapper.GetWallet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wallet/transactions", wrapper.ListTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games", wrapper.ListGames)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{gameId}/spin", wrapper.Spin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games/{gameId}/bonus", wrapper.GetActiveBonus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{gameId}/bonus/actions", wrapper.BonusAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spins", wrapper.ListSpins)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fzrchu3kn6VrtlUrVQ7JGXHJ7XR+aXYTqw6dqyylHhrTa8IzjQ5OMIAEwBDmnGpap9mH2yfZKsBzHBI",
	"gjfLcmV/SeRgcOn+8PUFDX5OMlVWSqK0Jjn/nFRMsxItavfpJ5wojZc5/Z+jyTSvLFcyOU/eoa21BG6x",
	"NDDntgAm4fIFCDVHDbZgEmzBDZxktTZKnyZpwum9P2rUiyRNJCsxOU/GboAkTUxWYMlonInSJbPJecKl",
	"/eFZkiZ2UaH/iFPUyf19mvzCyjAr12nFbLHsc+ofponGP2quMU/Ora6xO0bFrEVNr/7XB9b786z3Y+/j",
	"5yfpD8/uv1sOaKzmcurGe81Lbtvh1tYg3MNu9zlOWC1scv70b2lSsk+8rMvk/MnZWZqUXIZPkYXd05xN",
	"paRBL36Wv8M/ajRu7ExJi9L9y6pK8IyRLgb/NKSQz53hv9M4Sc6TfxksVTvwT83gpdYqDLWq0Es5Y4Ln",
	"wGVV2+Q+TZ4rORE8+wZDNyMFIGW11igtGMss0kx+VfZnVcv88Wfyq7IwcUPdp8mNUm+YXAQNmMcf/R2z",
	"CA5NSPAtkOVhH75Dqxe9i4lFvTrOJoTu0+Q3yWpbKM3/xG8kM8OnEgk7KSgNY5ZDpjFHaTkTxu2g0A2N",
	"clHb4kqrGW9WV2lVobbcg36q1FRgZ3FjpQQySSqpmDFzpfPY0/vuhv+wbJo2PX5sd5wa/xMzB/KLGbNM",
	"xwjurURQE7AFQqXRoAXm2sLlC5OkCUraxB8SzWYokzRRc0EUgLoiSdN6mWbjJE3mSkySNKkKhZJ/StLk",
	"jltTS8d5FYkgSZOJogeZKtF2ZtnwT5r8pGRtLjKa2dswv3Wpsaz5fuPtrFA8861Wl/i72/AzJmo0MFEa",
	"Rr7pKIV5gdKt3fcLlt2hAeWm7Tg/OlL4gmnNFhsKCTOMaaGzvg7fbVtgyT69Rjm1RXL+/dN023rXWv7w",
	"LNLSWKw2xXJTIIzo0agBgGMi918mOFETyyzmoGQfLqDkpmQ2K0A7k2jg2dmP6VDOC54VUDq55aoeC+xl",
	"gmd3BpjMqa3maMCwCfaHMm7lItILc94qxH9wT5MNPCca8dZUXBJmK57dJWkiWO5hNy8QCbWV4PJO0Rw0",
	"4/RFoUR+y2R+O+duarwkgaWJVrXF7Qi9doQdlWdVjwXPoGLaklAZjOmFINiSZQWX2IdXPM9RNog8wf60",
	"D/OCWWByKGtJ88ccLBcIxGmMS3MKEmeoQSCbeRUZ1DPUXqgxCEU2goee8ZtdsAVqKNkCDMocJH6yKbip",
	"jEiQoxRGNBH6mxVKGRx198QuCt3cxht7Jk3GaPf181yRPqktdejJq/Wa6prnSURDObOO41mecxqbiauO",
	"cLyDtCoVcrJ6psKMT0h1XoNeYycOUiBwYlPoqMWk4NEFupbT//3v/zlNIkidtt7bxizvAn73itEB3W1h",
	"ZuvDJH/tm27d97/W5Ri1g2eDB3aHEoyCCdORLZomVlkm3nN5oMbW9nSjvnTpsrr1t6vyaOgMk7YYDgrd",
	"xwfXrXgaRqAOZujNTSWQXI0dGxqrd2icK7vOx2MmmPQ0exBWVW3JwO1rf11x+TY0deKaIRPH4fY9MYYL",
	"PoLx8p1gDicEVQjukHFWDgUYnJYobQrb8GoaXjsIYtgg7HBcpMmcyxvunbtd7d+HZutI8jNcDrvsMG0V",
	"tRUjN5pPp37sNb6Ulme8Yo3hXY8AUZBLAN7SWeWo01OwUPNeruYSJDLds34AYJKXLJixdSeiu6nWGPF4",
	"5goIQGhGzjHjOeap83LogYfEckatsaGlTFU+lNQqGKlFOVbCQFYog856F2oOJZMLIPMKngvnqBHYnOkc",
	"89MVk74U99HsVinDt9gssqrNzKxbr18rMXEz9UMN01UYZq8PF+hpOa0YqDyoNyZ8JdiiVyqJC2ClqqXt",
	"w4WYswU5RBDUD7LlYNdL3znHe/IBafLc6MmNusOIX2ybrzeD+u7CfLPYanzcs9FvpvKIq/PGezI9jSxn",
	"Y4GA9DZQ48aH4NLUkwnPyI+8ndQyN6OYuS7RGDbF/TN3E1m2jy2BDPnLWYgA1zwfmHFTMwFIz1dcXLc1",
	"0ACXoHSOulnAnJNzmOeYj9KhHJW1sLwSHDV5RB6Rt1YzaUhx7jsfFN2WakahxUiwGbs1Fclo1B/KUYum",
	"EXDj/T2ah58Rm0wws+bvMCIaGAG5psY/a32ToQwe49ztUFOwCgEZ7WRWIuQqq4ngTcwnPIRcNgS6si0f",
	"uMPSxMtsR0AVeeAWfGi2bAXo9HgbSC7lREUsPdrXOENx+Gpbs7ZB5T4x9tMRPu4KXiOS4HFHUrCFqveO",
	"8tq1atjW5/MinWkMq9+kHq3mEa57p+aQEce5fAihOWQBQTdPnCmaMc2JJ3oF8mlhwc/axH1NNl3VQOPR",
	"SZy7mC2eO1hXgS1wyypnSjDLBbeLfWL7fdlyHV8u+HCCbIZqddHIMQhtZcC0g7IVmIR1RxGreSRvc+12",
	"E1y+MDBeAI0IJ5kSdSlPU08KE61KsKoil2WsrFVlH7wzQ0FfzicT1MDlUAqXO4CTNzhlZKhO+/AKP8FU",
	"89xAbRDUZGLQgu/enMOIhnMs5ojUfU0Ow1COtJqP/LcohMtzcgncekpqVXpoamXz8ytkwhabm9dsBADq",
	"LoKTiD9Zx6Xe2TIbsn+l5m6NJCGSgmPivA83zuOSOWrULlw0wK0JaA/6KLiz9s0sSd4EHS6R/maiNta5",
	"s2VQhkuQfopC/rWa8u2JJCwZF2vZoad/i6WHutnGTuMnT/99n/z8GJ0eYpJ8gxGX2+UY9+2/Nmt5nx4d",
	"h2UamcX8wq5Yj5xZ7Fnut+26HFqJbTwpmLnakZJt2HlvcqI2qBv23bWK35p2UdpppN72ljbyXIqpK4DV",
	"+cdU1Dx8hwbtcyUnXJebStuFk5LL9vNZjJ4b//Q4gPnX9gBsZfYP3g9RiEeHbXydjaGIHrea0ehxxuqY",
	"2ucrqXFs4Hc45cQS+5faArKBzIO4YJ+OH4zuDTrp9BkTxHXF5SturNKLS4tl1KU7Lsl40wSX8W3+BaSy",
	"IwlIAfWBWc35l+bewhid1JtPtfmM93I9e8R7FWK0VfFu2vN9Ka+utiLWXeIn68/iD5DKOjW6OWxbx9tl",
	"Wm4zvxBiwLyTtye5/R001gZzcrAmGrFHX7YZfaycIT8+lWSV691lj1DDGDNGThaDCTJba3TumWAuA3FE",
	"+sjFihEf3UXEBtjEogYmhJ96SAShzHtq4he2jHDN6aEZlWXIHQv4aKCj4HFtsXJZAS4v/TtPIi7hg5LR",
	"flKdXrYhZiu7Hk4q63lwtDtG+zrp56MZ77h873gtkbr3zabtbib8sqT5Efx5JGYenqjeQrvNQlfOOg7L",
	"Ybf7I3qE70IRlx7vw4XnFwq+KO7ImMlYjgYK5o62HQH04Wel20fpULqQkZ78q6H4rlQzzEfQZoCAaYRM",
	"INOYu9zwiEZsT46JuN3bQxmiwrFiOg+s0+Rvc60q4DKWn9rDXk3W3ddRAc6YqJnlcuoPQMK85/789+HM",
	"NQ0h984OqA1xVUubkSDdYtXhVTgJAu9yLaDN+qcpPPHFCNIXH0RcR6+Tr5OKO/7Y5nAip473JdidgEO/",
	"y+nEYH+jmTTLoog1c+sS7BG5+zqdrGByikBGuw2LDkizh8ZtGdJjxZs7CHEtntw+10OOWjoi9CnAWFAZ",
	"jjyCRNeEsM9TXB+hk4YxfCrr6rY5pyFmuvVc6P71fqh7Gv7PGReLtn2hat35qHHChYhmQzpz+Breahd3",
	"ez3VtRMgZgwwAyPPViNirynaJVFWbEo0PTYoLShfgCSYCQ8OAenBvu9vFUHwSqsJF7i96OjodMwXxXqb",
	"s+v00g1Nz1aCze/TlULWi95/+lrW24//9l1sX/2+kuBtgCjU3KXVcl6XBCw+LZI0maFe3Lr/Y5h6z4TA",
	"B3tl627gDiMfSHkbyx3GRFs4MRhhV8SFOZy4LLVLz8/ZwgxcCjKFkIEEw/9E9zB8YU6j/ENvbY71mkvs",
	"VWzhDqbI6RCL6Nu7bOcNOUhd4+lqOjGn3eSM/pxLOOlYzfgEv9kZlkvWbqziPVuY/ZJY9x79KN3Jt8y8",
	"BTU3URk+R4Fj7U/+Bc5QpP50X1JIuywi86lpkucAPDe3Zy7eG5HERzShMZ+G3DQ1qngWz7EbzGrN7eKa",
	"RNocJKs7jhe1T967+nL/1bLAvDK3Bo3xhRON5Cv+D1z4elweju3WcK0yzgS5slwquLi67MOFEKG6OlsA",
	"N9519EfyJ0N/bj9MTs+Bk3MspbIwJoe1nhZ2KF1ttkbCnj/El3mnFT3NNZuTEzuUL4k+/Olr8OxpOMJU",
	"7Qsnu5V67nggnDoblLlHAzD3/lBevnBDMdJASu/J5dm0L+WwtSavRrtQ0Y3v4rKec3PIF9ahhBtOrt5e",
	"3wyuLm6evxpc/XYzePHy9cubl6dQ1saP7Xoc/Ufv+fW7n3uupGA0lL4Q2xen03N3+Np4+KPK3GZGT0bg",
	"1ZY29TBLFBm0rlAGSSpD2ZT4+7INwbI7F36EmhFuBTpbKW2BSsK1qy65uLr0pGy8cs/6T/pnLkKsULKK",
	"J+fJ9/2z/vcuSWgLh6wBq20xoLm5smq0225xeDnSksHllZ283aRjCwQ+AYmYY04WmfjY7SNy2JJf0C5r",
	"MdYuMzw9O/tqxejLQWLXCdqFrOy55PzDx+YU9UNCskk+0nMvJl8jPsiYEGOW3XUktrZC1+550yxduTDz",
	"IX5BJJRobFTtL4kh/l5b1XXsi67qZOeLH9eU8/3Z0xg6cq4xs0BL9eYFYY5jsjjHi9ZYpu0euV67NkfN",
	"zSrw79JueHb2bBt02i4H7XWSw5cg1DQ4IMpEJu8OHMOFIzT2J5UvvhrUVw4z71ctotU13j/iNnuDsf11",
	"3Vz26MN1QxLBPgWK6HtdnO3XReeGk3vlyf5XVm630EtPf9z/0vpdnqNUHwpJtuq+KW5Y0cKzrdG3qm0f",
	"ngtkeovsDp5bcx7UcxdUBlnngDI613CCuXIu+EiwjZ6cHgTfZ/HAkToLiYvcezL4iRuX6goC9Lk4jTN1",
	"R7bpCyH4uGha05juBJ5RjYUhvrnGjiKciMZCZWfjm7lSa1ugBqWBPEZX4FcyHrRoUjDevKDMK8WlHcql",
	"b+nOmqyCnJtMkUPFMhfLuYK+v6aau9fb4vYO7eo9uEek8dWBIoz+3nmshk9lj0so0RYq97sJJRsLPMZU",
	"6nAIvwvTocXj4Hi9CuAgCD95ZJt54RELIV3oPexHtKMHoLu93/uo28GF91t3wWtu7C+uxQPhf/DRhitx",
	"3czCbypMCGigjLnPUuxYsX/eWfLgs89i3w/a08S9EVhNoaESM8zDYboKl+hdIB0IMgTKGZMu4KXI2kYD",
	"sQt30eenkCBeC1NiYlo2GYT79Rthwtdkpe4BamzD0OzDNYb7NG5lflXA1tp9mQt5dNhwqN4HnTuHcTbs",
	"XAp8mJq+PpNGruV+4wBk/RZaBCjuHozFqk00sZDFkTjv3jL9piHJcXj6loR9AHBNtSvWva74Xw6o3bKU",
	"b4zQTo3KFnBOaiFSqDT22vynK0Pw6Urya0M68/8DQh/3pyRil6PcDYqRPwjl8rbSaqrRmJE/32CrlnIo",
	"nal06dwxxYLBnE64NraJFr7m1inasvttXn4ozH9ECIYRYpka1DOeudy7n+hihwtjFsZiGdbljx63rekN",
	"Jt886/Q8/CpMbfz51RfAvqPDyh/8Jh9daa/Nis11+hPisNSvz1nRA+i/RH7PzyzvSPpbcdJRRjCqTcKu",
	"/7mLXSHHdfODGEcZMf8jUPfplp/C8teAmwAvFGT5Kiyi+8sXD/ktrC2Vvh8f2bJ1q5xjP/2DczTWs+vD",
	"92ThBwtanLclBttYKBQhPKIIwgixjIl70pZPPXjtYbXdpQ/sstJmN5xvug2/HNV7Gra/BfeoqFuvVnp0",
	"1C0lv2oZV0/mP3ykVfvzXC/WWovkPBmwig9mT5xMQo+f2+M7b1BJtOEblxfpfG54q/NVmE7nm5B6WH7R",
	"7JP7j/f/FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
