// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarId.
const (
	Comet   AvatarId = "comet"
	Fox     AvatarId = "fox"
	Kitsune AvatarId = "kitsune"
	Owl     AvatarId = "owl"
	Phoenix AvatarId = "phoenix"
	Raven   AvatarId = "raven"
	Scarab  AvatarId = "scarab"
	Serpent AvatarId = "serpent"
	Spider  AvatarId = "spider"
	Wolf    AvatarId = "wolf"
)

// Valid indicates whether the value is a known member of the AvatarId enum.
func (e AvatarId) Valid() bool {
	switch e {
	case Comet:
		return true
	case Fox:
		return true
	case Kitsune:
		return true
	case Owl:
		return true
	case Phoenix:
		return true
	case Raven:
		return true
	case Scarab:
		return true
	case Serpent:
		return true
	case Spider:
		return true
	case Wolf:
		return true
	default:
		return false
	}
}

// Defines values for BonusKind.
const (
	FreeSpins  BonusKind = "free_spins"
	HoldAndWin BonusKind = "hold_and_win"
	Ladder     BonusKind = "ladder"
	Pick       BonusKind = "pick"
	Plinko     BonusKind = "plinko"
	Route      BonusKind = "route"
	Timing     BonusKind = "timing"
	Trail      BonusKind = "trail"
	Wheel      BonusKind = "wheel"
)

// Valid indicates whether the value is a known member of the BonusKind enum.
func (e BonusKind) Valid() bool {
	switch e {
	case FreeSpins:
		return true
	case HoldAndWin:
		return true
	case Ladder:
		return true
	case Pick:
		return true
	case Plinko:
		return true
	case Route:
		return true
	case Timing:
		return true
	case Trail:
		return true
	case Wheel:
		return true
	default:
		return false
	}
}

// Defines values for BonusStatus.
const (
	Active    BonusStatus = "active"
	Completed BonusStatus = "completed"
)

// Valid indicates whether the value is a known member of the BonusStatus enum.
func (e BonusStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Completed:
		return true
	default:
		return false
	}
}

// Defines values for GameInfoTags.
const (
	Hot GameInfoTags = "hot"
	New GameInfoTags = "new"
)

// Valid indicates whether the value is a known member of the GameInfoTags enum.
func (e GameInfoTags) Valid() bool {
	switch e {
	case Hot:
		return true
	case New:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for LayoutKind.
const (
	Cluster  LayoutKind = "cluster"
	Hex      LayoutKind = "hex"
	Lines    LayoutKind = "lines"
	Megaways LayoutKind = "megaways"
	Ways     LayoutKind = "ways"
)

// Valid indicates whether the value is a known member of the LayoutKind enum.
func (e LayoutKind) Valid() bool {
	switch e {
	case Cluster:
		return true
	case Hex:
		return true
	case Lines:
		return true
	case Megaways:
		return true
	case Ways:
		return true
	default:
		return false
	}
}

// Defines values for TransactionKind.
const (
	BonusWin    TransactionKind = "bonus_win"
	DailyBonus  TransactionKind = "daily_bonus"
	HourlyBonus TransactionKind = "hourly_bonus"
	Refill      TransactionKind = "refill"
	SignupBonus TransactionKind = "signup_bonus"
	SpinBet     TransactionKind = "spin_bet"
	SpinWin     TransactionKind = "spin_win"
)

// Valid indicates whether the value is a known member of the TransactionKind enum.
func (e TransactionKind) Valid() bool {
	switch e {
	case BonusWin:
		return true
	case DailyBonus:
		return true
	case HourlyBonus:
		return true
	case Refill:
		return true
	case SignupBonus:
		return true
	case SpinBet:
		return true
	case SpinWin:
		return true
	default:
		return false
	}
}

// Defines values for Volatility.
const (
	High     Volatility = "high"
	Low      Volatility = "low"
	Medium   Volatility = "medium"
	VeryHigh Volatility = "very_high"
)

// Valid indicates whether the value is a known member of the Volatility enum.
func (e Volatility) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case VeryHigh:
		return true
	default:
		return false
	}
}

// Defines values for WinTier.
const (
	Big    WinTier = "big"
	Epic   WinTier = "epic"
	Mega   WinTier = "mega"
	None   WinTier = "none"
	Normal WinTier = "normal"
)

// Valid indicates whether the value is a known member of the WinTier enum.
func (e WinTier) Valid() bool {
	switch e {
	case Big:
		return true
	case Epic:
		return true
	case Mega:
		return true
	case None:
		return true
	case Normal:
		return true
	default:
		return false
	}
}

// AuthProviders defines model for AuthProviders.
type AuthProviders struct {
	Google   bool `json:"google"`
	Password bool `json:"password"`
}

// AvatarId One of the preset avatar IDs
type AvatarId string

// BonusActionOption defines model for BonusActionOption.
type BonusActionOption struct {
	Action string `json:"action"`

	// Choices Valid values for `choice`, when the action takes one
	Choices []string `json:"choices,omitempty,omitzero"`
}

// BonusActionRequest defines model for BonusActionRequest.
type BonusActionRequest struct {
	Action string `json:"action"`
	Choice string `json:"choice,omitempty,omitzero"`

	// Step The `step` of the state the client acted on. A mismatch returns 409,
	// which makes double-clicks and retries safe.
	Step int `json:"step"`
}

// BonusKind defines model for BonusKind.
type BonusKind string

// BonusState The public part of a bonus state machine. Hidden values (e.g. what an
// unpicked tile contains) never leave the server.
type BonusState struct {
	// Actions Actions the player may send next, e.g. `spin`, `pick`, `choose`
	Actions []BonusActionOption `json:"actions"`

	// Bet Play-money amount. Always an integer number of Coins.
	Bet     Coins              `json:"bet"`
	BonusId openapi_types.UUID `json:"bonusId"`

	// Data Game-specific public state (spins left, picked tiles, ladder rung…)
	Data   map[string]interface{} `json:"data"`
	GameId string                 `json:"gameId"`
	Kind   BonusKind              `json:"kind"`
	Status BonusStatus            `json:"status"`

	// Step Number of actions taken so far
	Step int `json:"step"`

	// TotalWin Play-money amount. Always an integer number of Coins.
	TotalWin Coins `json:"totalWin"`
}

// BonusStatus defines model for BonusStatus.
type BonusStatus string

// BonusStepResult defines model for BonusStepResult.
type BonusStepResult struct {
	// Balance Play-money amount. Always an integer number of Coins.
	Balance Coins `json:"balance"`

	// Outcome The animated part of a spin; reused by free-spin bonus steps.
	Outcome SpinOutcome `json:"outcome,omitempty,omitzero"`

	// Reveal What this action revealed (pick contents, wheel segment, …)
	Reveal map[string]interface{} `json:"reveal,omitempty,omitzero"`

	// State The public part of a bonus state machine. Hidden values (e.g. what an
	// unpicked tile contains) never leave the server.
	State BonusState `json:"state"`

	// StepWin Play-money amount. Always an integer number of Coins.
	StepWin Coins `json:"stepWin"`
}

// BonusTrigger defines model for BonusTrigger.
type BonusTrigger struct {
	// Anticipation Reels on which to play the slow-down near-trigger animation
	Anticipation []int     `json:"anticipation,omitempty,omitzero"`
	Kind         BonusKind `json:"kind"`

	// Positions The symbols that triggered the bonus
	Positions []Position `json:"positions"`
}

// Coins Play-money amount. Always an integer number of Coins.
type Coins = int64

// CsrfToken defines model for CsrfToken.
type CsrfToken struct {
	Token string `json:"token"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code, e.g. `insufficient_funds`
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GameEvent A visual event the client animates in order, e.g. `wild_added`,
// `multiplier`, `symbol_transform`, `serpent_move`, `lava_spread`.
// `positions` is what the event affects; `data` holds event-specific
// values whose shape each game documents.
type GameEvent struct {
	Data      map[string]interface{} `json:"data,omitempty,omitzero"`
	Positions []Position             `json:"positions,omitempty,omitzero"`
	Symbol    string                 `json:"symbol,omitempty,omitzero"`
	Type      string                 `json:"type"`
	Value     int64                  `json:"value,omitempty,omitzero"`
}

// GameInfo defines model for GameInfo.
type GameInfo struct {
	BetLevels []Coins `json:"betLevels"`

	// DefaultBet Play-money amount. Always an integer number of Coins.
	DefaultBet  Coins  `json:"defaultBet"`
	Description string `json:"description,omitempty,omitzero"`
	Id          string `json:"id"`

	// Layout How the grid is shaped. The renderer picks its layout from this.
	Layout LayoutKind `json:"layout"`
	Name   string     `json:"name"`
	Reels  int        `json:"reels"`

	// Rows Row count, or the maximum row count for variable-height layouts
	Rows       int            `json:"rows"`
	Tags       []GameInfoTags `json:"tags"`
	Theme      string         `json:"theme"`
	Volatility Volatility     `json:"volatility"`
}

// GameInfoTags defines model for GameInfo.Tags.
type GameInfoTags string

// Grid Symbol IDs by reel (column), each from top to bottom. Reels may differ in
// length (Megaways). Hex grids use offset columns: `reel` is the column and
// `row` the cell within it.
type Grid = [][]string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LayoutKind How the grid is shaped. The renderer picks its layout from this.
type LayoutKind string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	// Avatar One of the preset avatar IDs
	Avatar AvatarId `json:"avatar"`

	// Balance Play-money amount. Always an integer number of Coins.
	Balance     Coins              `json:"balance"`
	CreatedAt   time.Time          `json:"createdAt"`
	Email       string             `json:"email"`
	HasPassword bool               `json:"hasPassword"`
	Id          openapi_types.UUID `json:"id"`
	Username    Username           `json:"username"`
}

// PasswordResetConfirm defines model for PasswordResetConfirm.
type PasswordResetConfirm struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email string `json:"email"`
}

// Position defines model for Position.
type Position struct {
	Reel int `json:"reel"`
	Row  int `json:"row"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username Username            `json:"username"`
}

// SpinHistoryItem defines model for SpinHistoryItem.
type SpinHistoryItem struct {
	// Bet Play-money amount. Always an integer number of Coins.
	Bet            Coins              `json:"bet"`
	BonusTriggered bool               `json:"bonusTriggered,omitempty,omitzero"`
	CreatedAt      time.Time          `json:"createdAt"`
	GameId         string             `json:"gameId"`
	SpinId         openapi_types.UUID `json:"spinId"`

	// Win Play-money amount. Always an integer number of Coins.
	Win Coins `json:"win"`
}

// SpinHistoryPage defines model for SpinHistoryPage.
type SpinHistoryPage struct {
	Items      []SpinHistoryItem  `json:"items"`
	NextBefore openapi_types.UUID `json:"nextBefore,omitempty,omitzero"`
}

// SpinOutcome The animated part of a spin; reused by free-spin bonus steps.
type SpinOutcome struct {
	// Anticipation Reels to spin slower because a feature may land
	Anticipation []int `json:"anticipation,omitempty,omitzero"`

	// Events Events after all steps (e.g. end-of-spin multipliers)
	Events []GameEvent `json:"events,omitempty,omitzero"`
	Steps  []SpinStep  `json:"steps"`

	// TotalWin Play-money amount. Always an integer number of Coins.
	TotalWin Coins `json:"totalWin"`
}

// SpinRequest defines model for SpinRequest.
type SpinRequest struct {
	// Bet Play-money amount. Always an integer number of Coins.
	Bet Coins `json:"bet"`
}

// SpinResult defines model for SpinResult.
type SpinResult struct {
	// Balance Play-money amount. Always an integer number of Coins.
	Balance Coins `json:"balance"`

	// Bet Play-money amount. Always an integer number of Coins.
	Bet Coins `json:"bet"`

	// Bonus The public part of a bonus state machine. Hidden values (e.g. what an
	// unpicked tile contains) never leave the server.
	Bonus        BonusState   `json:"bonus,omitempty,omitzero"`
	BonusTrigger BonusTrigger `json:"bonusTrigger,omitempty,omitzero"`
	GameId       string       `json:"gameId"`

	// Outcome The animated part of a spin; reused by free-spin bonus steps.
	Outcome SpinOutcome        `json:"outcome"`
	SpinId  openapi_types.UUID `json:"spinId"`

	// TotalWin Play-money amount. Always an integer number of Coins.
	TotalWin Coins `json:"totalWin"`

	// WinTier Celebration level, chosen by the server from win / bet
	WinTier WinTier `json:"winTier"`
}

// SpinStep One grid state. A spin without cascades has one step. For cascades,
// each step's `removed` positions are cleared and `grid` of the next step
// is the board after symbols drop in.
type SpinStep struct {
	// Events Events to play before evaluating this step's wins
	Events []GameEvent `json:"events,omitempty,omitzero"`

	// Grid Symbol IDs by reel (column), each from top to bottom. Reels may differ in
	// length (Megaways). Hex grids use offset columns: `reel` is the column and
	// `row` the cell within it.
	Grid Grid `json:"grid"`

	// Multiplier Step multiplier (cascade multipliers etc.), 1 when none
	Multiplier int        `json:"multiplier,omitempty,omitzero"`
	Removed    []Position `json:"removed,omitempty,omitzero"`

	// StepWin Play-money amount. Always an integer number of Coins.
	StepWin Coins `json:"stepWin"`
	Wins    []Win `json:"wins"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Amount Signed change in balance
	Amount int64 `json:"amount"`

	// BalanceAfter Play-money amount. Always an integer number of Coins.
	BalanceAfter Coins           `json:"balanceAfter"`
	CreatedAt    time.Time       `json:"createdAt"`
	GameId       string          `json:"gameId,omitempty,omitzero"`
	Id           int64           `json:"id"`
	Kind         TransactionKind `json:"kind"`
}

// TransactionKind defines model for TransactionKind.
type TransactionKind string

// TransactionPage defines model for TransactionPage.
type TransactionPage struct {
	Items []Transaction `json:"items"`

	// NextBefore Pass as `before` to get the next page. Absent on the last page.
	NextBefore int64 `json:"nextBefore,omitempty,omitzero"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	// Avatar One of the preset avatar IDs
	Avatar   AvatarId `json:"avatar,omitempty,omitzero"`
	Username Username `json:"username,omitempty,omitzero"`
}

// Username defines model for Username.
type Username = string

// Volatility defines model for Volatility.
type Volatility string

// Wallet defines model for Wallet.
type Wallet struct {
	// Balance Play-money amount. Always an integer number of Coins.
	Balance Coins `json:"balance"`
}

// Win defines model for Win.
type Win struct {
	// Amount Play-money amount. Always an integer number of Coins.
	Amount Coins `json:"amount"`

	// Count Symbols matched (reels for ways/lines, cluster size for clusters)
	Count int `json:"count,omitempty,omitzero"`

	// Line Line-pay games only
	Line int `json:"line,omitempty,omitzero"`

	// Multiplier Total multiplier applied to this win (1 when none)
	Multiplier int        `json:"multiplier,omitempty,omitzero"`
	Positions  []Position `json:"positions"`
	Symbol     string     `json:"symbol"`

	// Ways Ways-pay games only
	Ways int `json:"ways,omitempty,omitzero"`
}

// WinTier Celebration level, chosen by the server from win / bet
type WinTier string

// BeforeId defines model for BeforeId.
type BeforeId = int64

// GameId defines model for GameId.
type GameId = string

// Limit defines model for Limit.
type Limit = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	Code  string `form:"code,omitempty" json:"code,omitempty,omitzero"`
	State string `form:"state,omitempty" json:"state,omitempty,omitzero"`
	Error string `form:"error,omitempty" json:"error,omitempty,omitzero"`
}

// ListSpinsParams defines parameters for ListSpins.
type ListSpinsParams struct {
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Before Return spins created before this spin ID (cursor)
	Before openapi_types.UUID `form:"before,omitempty" json:"before,omitempty,omitzero"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Before Return items with an ID lower than this (cursor)
	Before BeforeId `form:"before,omitempty" json:"before,omitempty,omitzero"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirm

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// BonusActionJSONRequestBody defines body for BonusAction for application/json ContentType.
type BonusActionJSONRequestBody = BonusActionRequest

// SpinJSONRequestBody defines body for Spin for application/json ContentType.
type SpinJSONRequestBody = SpinRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /auth/csrf)
	GetCsrfToken(w http.ResponseWriter, r *http.Request)

	// (GET /auth/google/callback)
	GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams)

	// (GET /auth/google/start)
	GoogleStart(w http.ResponseWriter, r *http.Request)

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/password-reset/confirm)
	ConfirmPasswordReset(w http.ResponseWriter, r *http.Request)

	// (POST /auth/password-reset/request)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)

	// (GET /auth/providers)
	GetAuthProviders(w http.ResponseWriter, r *http.Request)

	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)

	// (GET /games)
	ListGames(w http.ResponseWriter, r *http.Request)

	// (GET /games/{gameId}/bonus)
	GetActiveBonus(w http.ResponseWriter, r *http.Request, gameId GameId)

	// (POST /games/{gameId}/bonus/actions)
	BonusAction(w http.ResponseWriter, r *http.Request, gameId GameId)

	// (POST /games/{gameId}/spin)
	Spin(w http.ResponseWriter, r *http.Request, gameId GameId)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)

	// (GET /spins)
	ListSpins(w http.ResponseWriter, r *http.Request, params ListSpinsParams)

	// (GET /wallet)
	GetWallet(w http.ResponseWriter, r *http.Request)

	// (GET /wallet/transactions)
	ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /auth/csrf)
func (_ Unimplemented) GetCsrfToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/google/callback)
func (_ Unimplemented) GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/google/start)
func (_ Unimplemented) GoogleStart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/password-reset/confirm)
func (_ Unimplemented) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/password-reset/request)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/providers)
func (_ Unimplemented) GetAuthProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /games)
func (_ Unimplemented) ListGames(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /games/{gameId}/bonus)
func (_ Unimplemented) GetActiveBonus(w http.ResponseWriter, r *http.Request, gameId GameId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /games/{gameId}/bonus/actions)
func (_ Unimplemented) BonusAction(w http.ResponseWriter, r *http.Request, gameId GameId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /games/{gameId}/spin)
func (_ Unimplemented) Spin(w http.ResponseWriter, r *http.Request, gameId GameId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /me)
func (_ Unimplemented) UpdateMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /spins)
func (_ Unimplemented) ListSpins(w http.ResponseWriter, r *http.Request, params ListSpinsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /wallet)
func (_ Unimplemented) GetWallet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /wallet/transactions)
func (_ Unimplemented) ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCsrfToken operation middleware
func (siw *ServerInterfaceWrapper) GetCsrfToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCsrfToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleStart operation middleware
func (siw *ServerInterfaceWrapper) GoogleStart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleStart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthProviders operation middleware
func (siw *ServerInterfaceWrapper) GetAuthProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActiveBonus operation middleware
func (siw *ServerInterfaceWrapper) GetActiveBonus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", chi.URLParam(r, "gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveBonus(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BonusAction operation middleware
func (siw *ServerInterfaceWrapper) BonusAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", chi.URLParam(r, "gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BonusAction(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Spin operation middleware
func (siw *ServerInterfaceWrapper) Spin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", chi.URLParam(r, "gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Spin(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSpins operation middleware
func (siw *ServerInterfaceWrapper) ListSpins(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSpinsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSpins(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWallet operation middleware
func (siw *ServerInterfaceWrapper) GetWallet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWallet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/csrf", wrapper.GetCsrfToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset/request", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/providers", wrapper.GetAuthProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/start", wrapper.GoogleStart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/callback", wrapper.GoogleCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wallet", wrapper.GetWallet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wallet/transactions", wrapper.ListTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games", wrapper.ListGames)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{gameId}/spin", wrapper.Spin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games/{gameId}/bonus", wrapper.GetActiveBonus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{gameId}/bonus/actions", wrapper.BonusAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spins", wrapper.ListSpins)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fzrchu3kn6VrtlUrVw7JGXHJ7XR+aXITqw6dqyylHhrLa0IzjQ5OMIAEwBDmnGpap9mH2yfZKsBzHBI",
	"gjfLUmV/SeRgcOn+8PUFDX5JMlVWSqK0Jjn5klRMsxItavfpJxwrjec5/Z+jyTSvLFcyOUk+oK21BG6x",
	"NDDjtgAm4fwVCDVDDbZgEmzBDRxltTZKP0vShNN7f9So50maSFZicpKM3ABJmpiswJLROGOlS2aTk4RL",
	"+8PLJE3svEL/ESeok/v7NPmFlWFWrtOK2WLR58Q/TBONf9RcY56cWF1jd4yKWYuaXv2vT6z353Hvx97N",
	"l+fpDy/vv1sMaKzmcuLGe8tLbtvhVtYg3MNu9zmOWS1scvLib2lSss+8rMvk5PnxcZqUXIZPkYXd05xN",
	"paRBL36Wf8A/ajRu7ExJi9L9y6pK8IyRLgb/NKSQL53hv9M4Tk6SfxksVDvwT83gtdYqDLWs0HM5ZYLn",
	"wGVV2+Q+Tc6UHAuePcHQzUgBSFmtNUoLxjKLNJNflf1Z1TJ//Jn8qiyM3VD3aXKl1Dsm50ED5vFH/8As",
	"gkMTEnwLZHnYhx/Q6nnvdGxRL4+zDqH7NPlNstoWSvM/8YlkZvhEImEnBaVhxHLINOYoLWfCuB0UuqFR",
	"TmtbXGg15c3qKq0q1JZ70E+UmgjsLG6klEAmSSUVM2amdB57et/d8J8WTdOmx5t2x6nRPzFzID+dMst0",
	"jODeSwQ1BlsgVBoNWmCuLZy/MkmaoKRN/CnRbIoySRM1E0QBqCuSNK2XaTZK0mSmxDhJk6pQKPnnJE3u",
	"uDW1dJxXkQiSNBkrepCpEm1nlg3/pMlPStbmNKOZvQ/zW5Uay5rv197OCsUz32p5ib+7DT9lokYDY6Vh",
	"6JsOU5gVKN3afb9g2R0aUG7ajvOjI4UvmNZsvqaQMMOYFjrr6/DdpgWW7PNblBNbJCffv0g3rXel5Q8v",
	"Iy2NxWpdLFcFwpAeDRsAOCZy/2WCEzWxzGIOSvbhFEpuSmazArQziQZeHv+YXstZwbMCSie3XNUjgb1M",
	"8OzOAJM5tdUcDRg2xv61jFu5iPTCnDcK8R/c02QDz7FGvDUVl4TZimd3SZoIlnvYzQpEQm0luLxTNAfN",
	"OH1RKJHfMpnfzribGi9JYGmiVW1xM0IvHWFH5VnVI8EzqJi2JFQGI3ohCLZkWcEl9uENz3OUDSKPsD/p",
	"w6xgFpi8lrWk+WMOlgsE4jTGpXkGEqeoQSCbehUZ1FPUXqgxCEU2goee8ZtdsDlqKNkcDMocJH62Kbip",
	"DEmQwxSGNBH6mxVKGRx298Q2Cl3fxmt7Jk1GaHf1c6ZIn9SWOvTk1XpNdc3zJKKhnFnH8SzPOY3NxEVH",
	"ON5BWpYKOVk9U2HGx6Q6r0GvsSMHKRA4til01GJS8OgCXcvJ//73/zxLIkidtN7b2izvAn53itEB3W1h",
	"Zuv9JH/pm27c97/W5Qi1g2eDB3aHEoyCMdORLZomVlkmPnK5p8ZW9nSjvnThsrr1t6vyaOgMk7YYDgrd",
	"xQeXrXgaRqAOpujNTSWQXI0tGxqrD2icK7vKxyMmmPQ0uxdWVW3JwO1qf1lx+T40deKaIhOH4fYjMYYL",
	"PoLx8p1gDkcEVQjukHFWDgUYnJQobQqb8GoaXtsLYtgg7Ktx4cdbdJK2wt6o5yvNJxPvHK5wnrQ84xVr",
	"jOdqFIeCzDp4a2WVoz9Po0LNermaSZDIdM/6AYBJXrJgilYdge7GWGG1g/d1pQzfwNZkT8y8HClBjE26",
	"9nMjDirQW5Z9KfkiDLPTewkbczGtmCq8OtcmfCHYvFcqiXNgpaql7cOpmLE5uQIQhAayZR/XS9+5hTsi",
	"4TQ5M3p8pe4w4hHa5uv1cLa7MN8sthrv8a/1m6k8YuTfeRve08hyNhIISG8DNW6sJ5emHo95Rh7U7biW",
	"uRnGDFWJxrAJ7p65m8iifWwJZMJeT0Pss2LzYcpNzQQgPV9y7hzE0QCXoHSOulnAjJNblOeYD9NrOSxr",
	"YXklOGryBTwib61m0pDi3Hc+HLgt1ZSc6qFgU3ZrKpLRsH8thy2ahsCN93RoHn5GbDzGzJq/w5CYfgjk",
	"lBn/rLXK1zL4SrNCGQRTsAoBWVYAWRTIVVYTtZmYN7SPQ7Am0KVt+cAdliZeZltCicgDt+B980RLQKfH",
	"m0ByLscqYuPQvsUpiv1X25q71aWGlNBPB3h3S3iNSILHXSjB5qreOcpb16phW5/JinSmMax+nXq0mkW4",
	"7oOaQUYc5zIBhOaQ/wLdPHGh5pRpTjzRK5BPCgt+1ibuZbHJsgYaX0bizEUr8ah5VQW2wA2rnCrBLBfc",
	"zneJ7fdFy1V8ObfbCbIZqtVFI8cgtKUB0w7KlmAS1h1FrOaRjMWl201w/srAaA40IhxlStSlfJZ6Uhhr",
	"VYJVFRn6kbJWlX3wLgCFOzkfj1EDl9dSuKgZjt7hhJGhetaHN/gZJprnBmqDoMZjgxZ89+YEhjScYzFH",
	"pO5rCnSv5VCr2dB/i0K4DB+XwK2npFal+yYV1j+/QSYowl/dvGbN9VV3EZxEfK86LvXOllmT/Rs1c2sk",
	"CZEUHBPnfSBfRaPMUaN2gZIBbk1Ae9BHwZ21b2ZJ8ibocIn0NxO1sS5cL4MyXGrwcxTyb9WEb06hYEnh",
	"/XJe5MXfYomRbp6t0/j5i3/fJT8/RqeHmCTfYcRRddm1XfuvzdfdpwdHIJlGZjE/tUvWI2cWe5b7bbsq",
	"h1Zia08KZi62JCMbdt4ZltcGdcO+21bxW9MuSjuN1Nve0kaeCzF1BbA8/5iKmocf0KA9U3LMdbmutG04",
	"KblsPx/H6LnxTw8DmH9tB8CWZv/g/RCFeHTYxtdZG4rocaMZjSbyl8fUPlNHjWMDf8AJJ5bYvdQWkA1k",
	"HsQFu3T8YHSv0Umnz5ggLisu33BjlZ6fWyyjLt1h6bWrJriMb/OvIJUt6S9TcblnPm/21dkFP0Yn6eST",
	"TD7Xu1jPDvFehBhtWbzr9nxXsqerrYh1l/jZ+lPoPaSySo1uDpvW8X6RkFrPL4QYMO9krElufweNtcGc",
	"HKyxRuzRl20uGytnyA9PwFjlenc5F9QwwoyRk8VgjMzWGp17JpjLQByQdHGxYsRHdxGxATa2qIEJ4ace",
	"8u0o854a+4UtIlzzbN+MyiLkjgV8NNBB8Li0WLmsAJfn/p3nEZfwQWlYP6lOL5sQs5Fd9yeV1Qww2i2j",
	"fZvE68GMd1imc7SSftz5ZtN2OxN+Xbr4AP48EDOOH6/47jV+DM32pd1moUtZ/mas7Znfdn9ED69dKOJS",
	"yX049fxCwRfFHRkzGcvRQMHcoa4jgD78rHT7KL2WLmSkJ/9qKL4r1RTzIbQZIGAaIRPINObuTHNII7Zn",
	"pkTc7u1rGaLCkWI6D6zT5G9zrSrgMpaf2sFeTa7aVxABTpmomeVy4lP/Yd4zf/L5cOaahJB7awfUhriq",
	"pc1IkG6x6vAqHAWBd7kW0Gb9Zyk898fw0h+7R1xHr5Nvk4o76MDCIXR/IqeOdyXYnYBDv4vpxGB/pZk0",
	"i3KAFXPrEuwRufsKlaxgcoJARrsNi/ZIs4fGbQHOY8WbWwhxJZ7cPNd9jlo6IvQpwFhQGY48gkRXhLDL",
	"U1wdoZOGMXwi6+q2OachZrr1XOj+9X6oexr+zxkX87Z9oWrd+ahxzIWIZkM6c/gW3moXdzs91ZUTIGYM",
	"MANDz1ZDYq8J2gVRVmxCND0yKC0oX3ojmAkP9gHp3r7vbxVB8EKrMRe4udzm4HTMV8V667Pr9NINTY+X",
	"gs3v06USztPef/oqztubf/sutq9+X0rwNkAUaubSajmvSwIWnxRJmkxRz2/d/zFMfWRC4IO9slU3cIuR",
	"D6S8ieX2Y6INnBiMsCtfwhyOXJbapednbG4GLgWZQshAguF/onsYvjDPovxDb62P9ZZL7FVs7g6myOkQ",
	"8+jb22znFTlIXePpqhkxp93kjP6MSzjqWM34BJ/sDMsla9dW8ZHNzW5JrHqPfpTu5Ftm3oCaq6gMz1Dg",
	"SLtoFAROUaSQFcqgpJB2UT7lU9MkzwF4bm7PXLw3IomPaEIjPgm5aWpU8SyeYzeY1Zrb+SWJtDlIVncc",
	"T2ufvHeV1f6rRWl1ZW4NGuPLDRrJV/wfOPeVqDwc263gWmWcCXJluVRwenHeh1MhQl1xNgduvOvoj+SP",
	"rv25/XXy7AQ4OcdSKgsjcljrSWGvpatK1kjY84f4Mu+0oqe5ZjNyYq/la6IPf/oaPHsajjBV+5LBbo2a",
	"Ox4Ip84GZe7RAMy9fy3PX7mhGGkgpffk4mzauoMFW2vyarQLFd34Li7rOTeHfGEdipfh6OL95dXg4vTq",
	"7M3g4rerwavXb19fvX4GZW382K7H4X/0zi4//NxzJQXDa+lLkH1ZNj13h6+Nhz+szG1m9HgIXm1pU0Wy",
	"QJFB68pLkKRyLZvidl+2IVh258KPUADJrUBnK6UtUEm4dDVmpxfnnpSNV+5x/3n/2EWIFUpW8eQk+b5/",
	"3P/eJQlt4ZA1YLUtBjQ3V1CMdtP9BS9HWjK4vLKTt5t0bIHAxyARc8zJIhMfu31EDlvyC9pFLcZKGf+L",
	"4+NvVoa9GCRWSN8uZGnPJSefbppT1E8JySa5oedeTL46epAxIUYsu+tIbGWFrt1Z0yxduiryKX41IpRo",
	"rNWrL4gh/l5bAXXoi67qZOuLNyvK+f74RQwdOdeYWaClevOCMMMRWZzDRWss03aHXC9dm4PmZhX4d2k3",
	"vDx+uQk6bZeD9iLF/ksQahIcEGUik3cHjuGqDRr7k8rn3wzqS4eZ98sW0eoa7x9xm73D2P66bK459OGy",
	"IYlgnwJF9L0ujnfronO3x73yfPcrS/c66KUXP+5+afUWy0GqD4UkG3XfFDcsaeHlxuhb1bYPZwKZ3iC7",
	"vefWnAf13NWMQdY5oIzONZxgLp0LPhJsoyene8H3ZTxwpM5C4iL3ngx+5saluoIAfS5O41TdkW36Sgg+",
	"LppWNKY7gWdUY2GIJ9fYQYQT0Vio7Gx8M1dkbAvUoDSQx+gK/ErGgxZNCsabF5R5pbi013LhW7qzJqsg",
	"5yZT5FCxzMVyrqDvr6nm7sWuuL1Du3wD7BFpfHmgCKN/dB6r4RPZ4xJKtIXK/W5CyUYCDzGVOhzCb8N0",
	"aPE4OF6tAtgLws8f2WaeesRCSBd6D/sR7ege6G5vtj7qdnDh/cZd8JYb+4tr8UD473204Upc17Pw6woT",
	"AhooY+6zFFtW7J93ljz44rPY94P2NHFnBFZTaKjEFPNwmK7C9XEXSAeCDIFyxqQLeCmyttFA7NRdcfkp",
	"JIhXwpSYmBZNBuFm+VqY8C1ZqXuAGtswNPtwjeE+jVuZXxWwlXZf50IeHDbsq/dB57ZdnA071+EepqZv",
	"z6SRC6lPHICs3r+KAMXdg7FYtYkmFrI4Emfd+5VPGpIchqenJOw9gGuqbbHuZcX/ckDtlqU8MUI7NSob",
	"wDmuhUih0thr85+uDMGnK8mvDenM/w8IfdwfUYhdjnI3KIb+IJTL20qriUZjhv58gy1bymvpTKVL544o",
	"FgzmdMy1sU208C23TtGW3W/y8kNh/iNCMIwQy9SgnvLM5d79ROdbXBgzNxbLsC5/9LhpTe8wefKs01n4",
	"PZTa+POrr4B9R4eVP/hNblxpr82K9XX6E+Kw1G/PWdED6L9Efs/PLO9I+qk46SAjGNUmYdf/0MO2kOOy",
	"+SmIg4yY//mj+3TDj0D5HwNoArxQkOWrsIjuz1895FegNlT63jyyZetWOcd+9AZnaKxn14fvycIPFrQ4",
	"a0sMNrFQKEJ4RBGEEWIZE/ekLZ968NrDartLH9hFpc12OF91G349qnc0bH8F7VFRt1qt9OioW0h+2TIu",
	"n8x/uqFV+/NcL9Zai+QkGbCKD6bPnUxCj1/a4ztvUEm04RuXF+l8bnir81WYTuebkHpYfNHsk/ub+/8L",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
